### ISSUE TITLE
issue in sudo npm install 

### ISSUE THREAD

**Issue by Mujadded** [anik89/stock-market-ionic#1]
I am getting this error while writing sudo npm install

npm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid name: "KSCL Mobile App"
npm ERR!     at ensureValidName (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:284:15)
npm ERR!     at Object.module.exports.fixNameField (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:199:5)
npm ERR!     at /usr/lib/nodejs/normalize-package-data/lib/normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/lib/nodejs/normalize-package-data/lib/normalize.js:28:15)
npm ERR!     at final (/usr/lib/nodejs/read-package-json/read-json.js:310:33)
npm ERR!     at then (/usr/lib/nodejs/read-package-json/read-json.js:124:33)
npm ERR!     at /usr/lib/nodejs/read-package-json/read-json.js:299:40
npm ERR!     at fs.js:268:14
npm ERR!     at /usr/lib/nodejs/graceful-fs/graceful-fs.js:103:5
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.16.0-46-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/html/work/stock-market-ionic
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/html/work/stock-market-ionic/npm-debug.log
npm ERR! not ok code 0

**Comment by Mujadded** [comment]
I had to add "private":"true" and "name":"kscl mobile app" it seems capital letter accept kortesilo na and private field chara dependency install kortesilo na http://stackoverflow.com/questions/18401934/couldnt-read-dependencies-error-with-npm
